In [96]:
import numpy as np
sudoku = [
          [0,1,0,0,0,9,0,0,8],
          [2,0,7,0,3,0,0,0,0],
          [0,0,4,6,0,2,0,3,0],
          [3,7,8,4,0,0,0,0,9],
          [4,2,9,0,0,0,0,8,1],
          [0,6,1,9,2,8,4,0,0],
          [0,0,6,0,8,4,3,0,7],
          [0,4,0,0,9,0,0,1,0],
          [8,3,0,0,0,0,6,0,4]
         ]
print(np.matrix(sudoku1))

grid = sudoku

[[0 1 0 0 0 9 0 0 8]
 [2 0 7 0 3 0 0 0 0]
 [0 0 4 6 0 2 0 3 0]
 [3 7 8 4 0 0 0 0 9]
 [4 2 9 0 0 0 0 8 1]
 [0 6 1 9 2 8 4 0 0]
 [0 0 6 0 8 4 3 0 7]
 [0 4 0 0 9 0 0 1 0]
 [8 3 0 0 0 0 6 0 4]]


In [97]:
def possible(x,y,n) :
    global grid
    
    for i in range(0,9) :
        if grid[x][i] == n :
            return False
    for i in range(0,9) :
        if grid[i][y] == n :
            return False
    xq = (x//3)*3
    yq = (y//3)*3
    for i in range(3) :
        for j in range(0,3) :
            if grid[xq+i][yq+j] == n :
                return False
    return True

possible(0,0,5)

True

In [98]:
def solved() :
    global grid
    for i in range(9) :
        for j in range(9) :
            if grid[i][j] == 0 :
                return False
    return True
    
def solve() :
    global grid
    for i in range(9) :
        for j in range(9) :
            if grid[i][j] == 0 :
                ns = []     #list for all possible numbers for this cell
                for n in range(1,10) :
                    if possible(i,j,n) :
                        ns.append(n)
                if len(ns) == 1 :
                    grid[i][j] = ns[0]
                         
    print(np.matrix(grid))
    
    if not solved() :
        solve()
                        
solve()

[[0 1 0 0 0 9 0 0 8]
 [2 0 7 0 3 0 0 0 0]
 [0 0 4 6 0 2 0 3 5]
 [3 7 8 4 0 0 0 0 9]
 [4 2 9 0 0 0 0 8 1]
 [5 6 1 9 2 8 4 7 3]
 [0 0 6 0 8 4 3 0 7]
 [7 4 0 0 9 0 0 1 2]
 [8 3 0 0 0 0 6 0 4]]
[[6 1 0 0 0 9 0 0 8]
 [2 0 7 0 3 0 0 0 6]
 [9 8 4 6 0 2 0 3 5]
 [3 7 8 4 0 0 0 0 9]
 [4 2 9 0 0 0 5 8 1]
 [5 6 1 9 2 8 4 7 3]
 [1 0 6 0 8 4 3 0 7]
 [7 4 5 3 9 6 8 1 2]
 [8 3 2 0 0 0 6 0 4]]
[[6 1 3 0 0 9 0 0 8]
 [2 5 7 0 3 1 9 4 6]
 [9 8 4 6 7 2 1 3 5]
 [3 7 8 4 0 5 2 6 9]
 [4 2 9 7 6 3 5 8 1]
 [5 6 1 9 2 8 4 7 3]
 [1 9 6 0 8 4 3 5 7]
 [7 4 5 3 9 6 8 1 2]
 [8 3 2 0 0 7 6 9 4]]
[[6 1 3 5 4 9 7 2 8]
 [2 5 7 8 3 1 9 4 6]
 [9 8 4 6 7 2 1 3 5]
 [3 7 8 4 1 5 2 6 9]
 [4 2 9 7 6 3 5 8 1]
 [5 6 1 9 2 8 4 7 3]
 [1 9 6 2 8 4 3 5 7]
 [7 4 5 3 9 6 8 1 2]
 [8 3 2 1 5 7 6 9 4]]


In [99]:
def solve2() :
    global grid
    for i in range(9) :
        for j in range(9) :
            if grid[i][j] == 0 :
                for n in range(1,10) :
                    if possible(i,j,n) :
                        grid[i][j] = n
                        solve2()
                        grid[i][j] = 0
                return
    print(np.matrix(grid))
    
solve2()

[[6 1 3 5 4 9 7 2 8]
 [2 5 7 8 3 1 9 4 6]
 [9 8 4 6 7 2 1 3 5]
 [3 7 8 4 1 5 2 6 9]
 [4 2 9 7 6 3 5 8 1]
 [5 6 1 9 2 8 4 7 3]
 [1 9 6 2 8 4 3 5 7]
 [7 4 5 3 9 6 8 1 2]
 [8 3 2 1 5 7 6 9 4]]
