In [91]:
import numpy as np
sudoku1 = [
          [0,1,0,0,0,9,0,0,8],
          [2,0,7,0,3,0,0,0,0],
          [0,0,4,6,0,2,0,3,0],
          [3,7,8,4,0,0,0,0,9],
          [4,2,9,0,0,0,0,8,1],
          [0,6,1,9,2,8,4,0,0],
          [0,0,6,0,8,4,3,0,7],
          [0,4,0,0,9,0,0,1,0],
          [8,3,0,0,0,0,6,0,4]
         ]
print(np.matrix(sudoku1))
sudoku2 = [
          [2,0,0,0,0,0,0,4,3],
          [0,0,0,4,0,9,0,2,0],
          [0,4,0,5,0,6,0,0,0],
          [0,6,5,3,0,0,9,0,0],
          [0,0,0,6,7,4,0,0,5],
          [3,0,4,0,0,8,2,0,1],
          [9,1,0,8,0,0,0,0,0],
          [0,0,0,1,0,5,7,0,0],
          [6,0,0,0,0,7,0,0,0]
         ]
print(np.matrix(sudoku2))
grid = sudoku2

[[0 1 0 0 0 9 0 0 8]
 [2 0 7 0 3 0 0 0 0]
 [0 0 4 6 0 2 0 3 0]
 [3 7 8 4 0 0 0 0 9]
 [4 2 9 0 0 0 0 8 1]
 [0 6 1 9 2 8 4 0 0]
 [0 0 6 0 8 4 3 0 7]
 [0 4 0 0 9 0 0 1 0]
 [8 3 0 0 0 0 6 0 4]]
[[2 0 0 0 0 0 0 4 3]
 [0 0 0 4 0 9 0 2 0]
 [0 4 0 5 0 6 0 0 0]
 [0 6 5 3 0 0 9 0 0]
 [0 0 0 6 7 4 0 0 5]
 [3 0 4 0 0 8 2 0 1]
 [9 1 0 8 0 0 0 0 0]
 [0 0 0 1 0 5 7 0 0]
 [6 0 0 0 0 7 0 0 0]]


In [77]:
def possible(x,y,n) :
    global grid
    
    for i in range(0,9) :
        if grid[x][i] == n :
            return False
    for i in range(0,9) :
        if grid[i][y] == n :
            return False
    xq = (x//3)*3
    yq = (y//3)*3
    for i in range(3) :
        for j in range(0,3) :
            if grid[xq+i][yq+j] == n :
                return False
    return True

possible(0,0,5)

False

In [92]:
def solved() :
    global grid
    for i in range(9) :
        for j in range(9) :
            if grid[i][j] == 0 :
                return False
    return True
    
def solve() :
    global grid
    for i in range(9) :
        for j in range(9) :
            if grid[i][j] == 0 :
                ns = []     #list for all possible numbers for this cell
                for n in range(1,10) :
                    if possible(i,j,n) :
                        ns.append(n)
                if len(ns) == 1 :
                    grid[i][j] = ns[0]
                         
    print(np.matrix(grid))
    
    if not solved() :
        solve()
                        
solve()

[[2 0 0 7 0 1 0 4 3]
 [0 0 0 4 0 9 0 2 0]
 [0 4 0 5 0 6 0 0 0]
 [0 6 5 3 0 2 9 0 0]
 [0 0 0 6 7 4 0 0 5]
 [3 0 4 9 5 8 2 0 1]
 [9 1 0 8 0 3 0 0 0]
 [0 0 0 1 0 5 7 0 0]
 [6 0 0 2 0 7 0 0 0]]
[[2 0 0 7 8 1 0 4 3]
 [0 0 0 4 3 9 0 2 0]
 [0 4 0 5 2 6 0 0 0]
 [0 6 5 3 1 2 9 0 0]
 [0 0 0 6 7 4 0 0 5]
 [3 7 4 9 5 8 2 6 1]
 [9 1 0 8 0 3 0 5 0]
 [0 0 0 1 0 5 7 0 0]
 [6 0 0 2 0 7 0 0 0]]
[[2 0 0 7 8 1 0 4 3]
 [0 0 0 4 3 9 0 2 0]
 [0 4 0 5 2 6 0 0 0]
 [8 6 5 3 1 2 9 7 4]
 [1 0 0 6 7 4 0 0 5]
 [3 7 4 9 5 8 2 6 1]
 [9 1 0 8 0 3 0 5 0]
 [4 0 0 1 0 5 7 0 0]
 [6 0 0 2 0 7 0 0 0]]
[[2 0 0 7 8 1 0 4 3]
 [0 0 0 4 3 9 0 2 0]
 [7 4 0 5 2 6 0 0 0]
 [8 6 5 3 1 2 9 7 4]
 [1 0 0 6 7 4 0 0 5]
 [3 7 4 9 5 8 2 6 1]
 [9 1 0 8 0 3 0 5 0]
 [4 0 0 1 0 5 7 0 0]
 [6 0 0 2 0 7 0 0 0]]
[[2 0 0 7 8 1 0 4 3]
 [5 8 0 4 3 9 0 2 0]
 [7 4 0 5 2 6 0 0 0]
 [8 6 5 3 1 2 9 7 4]
 [1 0 0 6 7 4 0 0 5]
 [3 7 4 9 5 8 2 6 1]
 [9 1 0 8 0 3 0 5 0]
 [4 0 0 1 0 5 7 0 0]
 [6 0 0 2 0 7 0 0 0]]
[[2 9 6 7 8 1 5 4 3]
 [5 8 1 4 3 9 6 2 7]
 [7 4 3 

In [63]:
ns = []
ns.append(5)
ns.append(6)
len(ns)

2

In [84]:
def solve2() :
    global grid
    for i in range(9) :
        for j in range(9) :
            if grid[i][j] == 0 :
                for n in range(1,10) :
                    if possible(i,j,n) :
                        grid[i][j] = n
                        solve2()
                        grid[i][j] = 0
                return
    print(np.matrix(grid))
    
solve2()

[[2 7 9 5 8 1 6 4 3]
 [1 3 6 4 7 9 5 2 8]
 [5 4 8 2 3 6 1 9 7]
 [7 6 5 3 1 2 9 8 4]
 [8 2 1 6 9 4 3 7 5]
 [3 9 4 7 5 8 2 6 1]
 [9 1 7 8 2 3 4 5 6]
 [4 8 2 1 6 5 7 3 9]
 [6 5 3 9 4 7 8 1 2]]
[[2 7 9 5 8 1 6 4 3]
 [1 3 6 4 7 9 5 2 8]
 [5 4 8 2 3 6 1 9 7]
 [7 6 5 3 1 2 9 8 4]
 [8 2 1 6 9 4 3 7 5]
 [3 9 4 7 5 8 2 6 1]
 [9 1 7 8 2 5 4 3 6]
 [4 8 2 1 6 3 7 5 9]
 [6 5 3 9 4 7 8 1 2]]
[[2 7 9 5 8 1 6 4 3]
 [1 3 6 4 7 9 5 2 8]
 [5 4 8 2 3 6 1 9 7]
 [8 6 5 3 1 2 9 7 4]
 [7 2 1 6 9 4 3 8 5]
 [3 9 4 7 5 8 2 6 1]
 [9 1 7 8 2 3 4 5 6]
 [4 8 2 1 6 5 7 3 9]
 [6 5 3 9 4 7 8 1 2]]
[[2 7 9 5 8 1 6 4 3]
 [1 3 6 4 7 9 5 2 8]
 [5 4 8 2 3 6 1 9 7]
 [8 6 5 3 1 2 9 7 4]
 [7 2 1 6 9 4 3 8 5]
 [3 9 4 7 5 8 2 6 1]
 [9 1 7 8 2 5 4 3 6]
 [4 8 2 1 6 3 7 5 9]
 [6 5 3 9 4 7 8 1 2]]
[[2 7 9 5 8 1 6 4 3]
 [1 8 6 4 3 9 5 2 7]
 [5 4 3 2 7 6 1 8 9]
 [8 6 5 3 1 2 9 7 4]
 [7 2 1 6 9 4 8 3 5]
 [3 9 4 7 5 8 2 6 1]
 [9 1 7 8 2 3 4 5 6]
 [4 3 2 1 6 5 7 9 8]
 [6 5 8 9 4 7 3 1 2]]
[[2 7 9 5 8 1 6 4 3]
 [1 8 6 4 3 9 5 2 7]
 [5 4 3 

[[2 9 6 7 1 5 8 4 3]
 [7 8 1 4 3 9 5 2 6]
 [5 4 3 2 8 6 1 9 7]
 [8 6 5 3 2 1 9 7 4]
 [1 2 9 6 7 4 3 8 5]
 [3 7 4 5 9 8 2 6 1]
 [9 1 7 8 4 3 6 5 2]
 [4 5 8 1 6 2 7 3 9]
 [6 3 2 9 5 7 4 1 8]]
[[2 9 6 7 1 5 8 4 3]
 [7 8 1 4 3 9 5 2 6]
 [5 4 3 2 8 6 1 9 7]
 [8 6 5 3 2 1 9 7 4]
 [1 2 9 6 7 4 3 8 5]
 [3 7 4 9 5 8 2 6 1]
 [9 1 7 8 4 3 6 5 2]
 [4 5 8 1 6 2 7 3 9]
 [6 3 2 5 9 7 4 1 8]]
[[2 9 6 7 5 1 8 4 3]
 [5 3 1 4 8 9 6 2 7]
 [7 4 8 2 3 6 1 5 9]
 [1 6 5 3 7 2 9 8 4]
 [8 2 9 6 1 4 3 7 5]
 [3 7 4 5 9 8 2 6 1]
 [9 1 7 8 2 5 4 3 6]
 [4 5 2 1 6 3 7 9 8]
 [6 8 3 9 4 7 5 1 2]]
[[2 9 6 7 5 1 8 4 3]
 [5 3 1 4 8 9 6 2 7]
 [7 4 8 2 3 6 1 5 9]
 [8 6 5 3 1 2 9 7 4]
 [1 2 9 6 7 4 3 8 5]
 [3 7 4 5 9 8 2 6 1]
 [9 1 7 8 2 5 4 3 6]
 [4 5 2 1 6 3 7 9 8]
 [6 8 3 9 4 7 5 1 2]]
[[2 9 6 7 5 1 8 4 3]
 [5 3 1 4 8 9 6 2 7]
 [7 4 8 2 3 6 5 1 9]
 [1 6 5 3 7 2 9 8 4]
 [8 2 9 6 1 4 3 7 5]
 [3 7 4 5 9 8 2 6 1]
 [9 1 7 8 2 3 4 5 6]
 [4 8 3 1 6 5 7 9 2]
 [6 5 2 9 4 7 1 3 8]]
[[2 9 6 7 5 1 8 4 3]
 [5 3 1 4 8 9 6 2 7]
 [7 4 8 

[[2 9 8 7 5 1 6 4 3]
 [5 3 6 4 8 9 1 2 7]
 [7 4 1 2 3 6 5 8 9]
 [8 6 5 3 1 2 9 7 4]
 [1 2 9 6 7 4 8 3 5]
 [3 7 4 5 9 8 2 6 1]
 [9 1 7 8 2 3 4 5 6]
 [4 8 3 1 6 5 7 9 2]
 [6 5 2 9 4 7 3 1 8]]
[[2 9 8 7 5 1 6 4 3]
 [5 3 6 4 8 9 1 2 7]
 [7 4 1 2 3 6 5 8 9]
 [8 6 5 3 1 2 9 7 4]
 [1 2 9 6 7 4 8 3 5]
 [3 7 4 5 9 8 2 6 1]
 [9 1 7 8 6 3 4 5 2]
 [4 8 3 1 2 5 7 9 6]
 [6 5 2 9 4 7 3 1 8]]
[[2 9 8 7 5 1 6 4 3]
 [5 3 6 4 8 9 1 2 7]
 [7 4 1 2 3 6 5 9 8]
 [1 6 5 3 7 2 9 8 4]
 [8 2 9 6 1 4 3 7 5]
 [3 7 4 5 9 8 2 6 1]
 [9 1 7 8 2 3 4 5 6]
 [4 8 2 1 6 5 7 3 9]
 [6 5 3 9 4 7 8 1 2]]
[[2 9 8 7 5 1 6 4 3]
 [5 3 6 4 8 9 1 2 7]
 [7 4 1 2 3 6 5 9 8]
 [1 6 5 3 7 2 9 8 4]
 [8 2 9 6 1 4 3 7 5]
 [3 7 4 5 9 8 2 6 1]
 [9 1 7 8 2 5 4 3 6]
 [4 8 2 1 6 3 7 5 9]
 [6 5 3 9 4 7 8 1 2]]
[[2 9 8 7 5 1 6 4 3]
 [5 3 6 4 8 9 1 2 7]
 [7 4 1 2 3 6 5 9 8]
 [8 6 5 3 1 2 9 7 4]
 [1 2 9 6 7 4 3 8 5]
 [3 7 4 5 9 8 2 6 1]
 [9 1 7 8 2 3 4 5 6]
 [4 8 2 1 6 5 7 3 9]
 [6 5 3 9 4 7 8 1 2]]
[[2 9 8 7 5 1 6 4 3]
 [5 3 6 4 8 9 1 2 7]
 [7 4 1 